[package]
name = "mandelbrot_par"
version = "0.1.0"
authors = ["Jared Moulton <jaredmoulton3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
